-- AlterTable
ALTER TABLE "Character" ADD COLUMN     "itemData" JSONB NOT NULL DEFAULT '[]';

-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "containerCapacity" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "containerHeight" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "containerWidth" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "height" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "isContainer" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "stackCapacity" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "weight" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "width" INTEGER NOT NULL DEFAULT 2;
