import accordionTheme from '../components/accordion/theme';
import appBarTheme from '../components/app-bar/theme';
import autocompleteTheme from '../components/autocomplete/theme';
import avatarTheme from '../components/avatar/theme';
import backdropTheme from '../components/backdrop/theme';
import breadcrumbsTheme from '../components/breadcrumbs/theme';
import buttonTheme from '../components/button/theme';
import cardTheme from '../components/card/theme';
import checkboxTheme from '../components/checkbox/theme';
import chipTheme from '../components/chip/theme';
import dialogTheme from '../components/dialog/theme';
import dividerTheme from '../components/divider/theme';
import drawerTheme from '../components/drawer/theme';
import fabTheme from '../components/fab/theme';
import iconButtonTheme from '../components/icon-button/theme';
import inputTheme from '../components/input/theme';
import listTheme from '../components/list/theme';
import loaderTheme from '../components/loader/theme';
import menuTheme from '../components/menu/theme';
import paperTheme from '../components/paper/theme';
import progressTheme from '../components/progress/theme';
import radioTheme from '../components/radio/theme';
import selectTheme from '../components/select/theme';
import skeletonTheme from '../components/skeleton/theme';
import sliderTheme from '../components/slider/theme';
import speedDialTheme from '../components/speed-dial/theme';
import stackTheme from '../components/stack/theme';
import stepperTheme from '../components/stepper/theme';
import switchTheme from '../components/switch/theme';
import tabsTheme from '../components/tabs/theme';
import textTheme from '../components/text/theme';
import toggleButtonTheme from '../components/toggle-button/theme';
import toolbarTheme from '../components/toolbar/theme';
import tooltipTheme from '../components/tooltip/theme';

export const injectTheme = (): void => {
  accordionTheme();
  appBarTheme();
  autocompleteTheme();
  avatarTheme();
  backdropTheme();
  breadcrumbsTheme();
  buttonTheme();
  cardTheme();
  checkboxTheme();
  chipTheme();
  dialogTheme();
  drawerTheme();
  dividerTheme();
  fabTheme();
  iconButtonTheme();
  inputTheme();
  listTheme();
  loaderTheme();
  menuTheme();
  paperTheme();
  progressTheme();
  radioTheme();
  selectTheme();
  skeletonTheme();
  sliderTheme();
  speedDialTheme();
  stackTheme();
  stepperTheme();
  switchTheme();
  tabsTheme();
  textTheme();
  toggleButtonTheme();
  tooltipTheme();
  toolbarTheme();
};
