import {
  testResolvers,
  userResolvers,
  imageResolvers,
  rulesetResolvers,
  archetypeResolvers,
  attributeResolvers,
  characterResolvers,
  chartResolvers,
  componentResolvers,
  documentResolvers,
  pageResolvers,
  sheetResolvers,
  subscriptionResolvers,
} from './services';

export const resolvers = {
  Query: {
    ...testResolvers.Query,
    ...userResolvers.Query,
    ...imageResolvers.Query,
    ...rulesetResolvers.Query,
    ...archetypeResolvers.Query,
    ...attributeResolvers.Query,
    ...characterResolvers.Query,
    ...chartResolvers.Query,
    ...componentResolvers.Query,
    ...documentResolvers.Query,
    ...pageResolvers.Query,
    ...sheetResolvers.Query,
  },
  Mutation: {
    ...userResolvers.Mutation,
    ...imageResolvers.Mutation,
    ...rulesetResolvers.Mutation,
    ...archetypeResolvers.Mutation,
    ...attributeResolvers.Mutation,
    ...characterResolvers.Mutation,
    ...chartResolvers.Mutation,
    ...componentResolvers.Mutation,
    ...documentResolvers.Mutation,
    ...pageResolvers.Mutation,
    ...sheetResolvers.Mutation,
  },
  Subscription: {
    ...subscriptionResolvers,
  },
};
